ALL_ACTORS:
  - 己方
  - 敌方
  - 敌人
  - 对方
  - 对手
  - 中立

ALL_DIRECTIONS:
  - 上
  - 下
  - 左
  - 右
  - 东
  - 西
  - 南
  - 北
  - 左上
  - 右上
  - 左下
  - 右下
  - 东北
  - 西北
  - 东南
  - 西南
  - 附近
  - 左右
  - 旁边

ALL_GROUPS:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9

ALL_REGIONS:
  - 地图中央
  - 地图左上
  - 地图上方
  - 地图右上
  - 地图右侧
  - 地图右下
  - 地图下方
  - 地图左下
  - 地图左侧
  - 视线范围
  - 全地图
  - 全屏幕
  - 屏幕中央
  - 屏幕左上
  - 屏幕上方
  - 屏幕右上
  - 屏幕右侧
  - 屏幕右下
  - 屏幕下方
  - 屏幕左下
  - 屏幕左侧

ALL_RELATIVES:
  - 上方
  - 下方
  - 左侧
  - 右侧
  - 左上方
  - 左下方
  - 右上方
  - 右下方
  - 中央
  - 中间
  - 左边
  - 右边
  - 上边
  - 下边

ALL_BUILDINGS:
  - 基地
  - 电
  - 小电
  - 小电厂
  - 电厂
  - 发电厂
  - 兵营
  - 矿场
  - 采矿场
  - 矿
  - 坦克厂
  - 车间
  - 坦克工厂
  - 雷达
  - 维修厂
  - 修理厂
  - 大电厂
  - 核电厂
  - 机场
  - 科技中心
  - 高科技
  - 狗屋

ALL_DEFENSE_DEVICES:
  - 储油罐
  - 井
  - 存钱罐
  - 喷火塔
  - 喷火碉堡
  - 特斯拉线圈
  - 特斯拉塔
  - 电塔
  - 防空塔
  - 防空
  - 铁幕
  - 铁幕装置
  - 导弹发射井
  - 核弹

ALL_INFANTRIES:
  - 步兵
  - 枪兵
  - 导弹兵
  - 火箭筒
  - 炮兵
  - 掷弹兵
  - 狗
  - 小狗
  - 军犬
  - 工程师
  - 喷火兵
  - 间谍
  - 电兵
  - 突击兵
  - 士兵

ALL_TANKS:
  - 矿车
  - 采矿车
  - 吉普
  - 装甲车
  - 运兵车
  - 防空车
  - 基地车
  - mcv
  - 轻坦克
  - 轻坦
  - 重坦
  - 犀牛
  - V2
  - 火箭炮
  - 雷车
  - 布雷车
  - 猛犸
  - 天启
  - 磁能坦克
  - 特斯拉坦克
  - 磁暴坦克
  - 卡车
  - 补给车
  - 地震车
  - 震荡坦克
  - 飞机
  - 载具
  - 坦克
