nodes:
  - id: ra-terminal-input
    build: pip install -e ./agent-hub/ra-terminal-input
    path: dynamic
    outputs:
      - data

  - id: ra-classify
    build: pip install -e ./agent-hub/ra-classify
    path: ra-classify
    outputs:
      - assistant
      - produce
      - camera
      - unit
      - info
      - terminal_output
    inputs:
      command: ra-terminal-input/data

  - id: ra-camera
    build: pip install -e ./agent-hub/ra-camera
    path: ra-camera
    outputs:
      - camera_result
      - terminal_output
    inputs:
      command: ra-classify/camera
    
  - id: ra-produce
    build: pip install -e ./agent-hub/ra-produce
    path: ra-produce
    outputs:
      - produce_result
      - terminal_output
    inputs:
      command: ra-classify/produce

  - id: ra-unit
    build: pip install -e ./agent-hub/ra-unit
    path: ra-unit
    outputs:
      - unit_result
      - terminal_output
    inputs:
      command: ra-classify/unit

  - id: ra-info
    build: pip install -e ./agent-hub/ra-info
    path: ra-info
    outputs:
      - info_result
      - terminal_output
    inputs:
      command: ra-classify/info
    
  - id: ra-ai_assistant
    build: pip install -e ./agent-hub/ra-ai_assistant
    path: ra-ai_assistant
    outputs:
      - ai_assistant_result
      - terminal_output
    inputs:
      data: ra-classify/assistant

  - id: show-result
    build: pip install -e ./agent-hub/show-result
    path: show-result
    inputs:
      data: ra-classify/assistant

