[project]
name = "ra-ai_assistant"
version = "0.0.1"
authors = [
    {name = "Mofa Bot"}
]
description = "ra-ai_assistant"
license = {text = "MIT"}
dependencies = [
    "python-dotenv>=1.0.0"
]
requires-python = ">=3.10,<3.13"

[project.scripts]
ra-ai_assistant = "ai_assistant.main:main"

[tool.setuptools.packages.find]
include = ["ai_assistant*"]

[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"
